services:
  fastapi_app:
    container_name: fastapi_app
    build: 
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./service:/service
    depends_on:
      - database
    env_file:
      - ./.env
    command: >
      sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

  database:
    image: postgres:latest
    container_name: database
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_database:/var/lib/postgresql/data/
      
  test_database:
    image: postgres:latest
    container_name: test_database
    # env_file:
    #   - ./.env_test
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_database:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - database
      - test_database

  redis:
    container_name: redis
    image: redis:7.0.5-alpine
    hostname: redis
    ports:
      - "6379:6379"

  worker1:
    build: .
    container_name: worker1
    hostname: worker1
    entrypoint: celery
    command: -A tasks.celery_app worker --loglevel=info
    env_file:
      - ./.env
    volumes:
      - ./service:/service
    links:
      - redis
    depends_on:
      - redis
      - database

  worker2:
    build: .
    container_name: worker2
    hostname: worker2
    entrypoint: celery
    command: -A tasks.celery_app worker --loglevel=info
    env_file:
      - ./.env
    volumes:
      - ./service:/service
    links:
      - redis
    depends_on:
      - redis
      - database

  flower:
    build: .
    container_name: flower
    hostname: flower
    entrypoint: celery
    command: -A tasks.celery_app flower
    env_file:
      - ./.env
    volumes:
      - ./service:/service
    links:
      - redis
    depends_on:
      - redis
    ports:
      - "5555:5555"

volumes:
  postgres_database:
  postgres_test_database: